[package]
name = "audioserve"
version = "0.8.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]

[dependencies]
pretty_env_logger = "0.2"
log = "0.4"
hyper = "0.12"
hyperx= "0.13"
futures = "0.1"
mime = "0.3"
mime_guess = "2.0.0-alpha.4"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
clap = "2"
lazy_static = "1.2.0"
quick-error = "1.2"
url = "1.7"
percent-encoding = "1.0"
num_cpus = "1.8"
ring = "0.13"
data-encoding = "2.1"
regex = "1.1"
tokio = "0.1.13"
tokio-process = "0.2"
tokio-threadpool = "0.1"
dirs = "1.0"
taglib = "1.0"

# for ssl
tokio-tls = {version="0.2", optional=true}
native-tls = {version="0.2", optional=true}

cachedirtree = {git="https://github.com/izderadicka/cachedirtree.git", optional=true}

bytes = {version="0.4", optional=true}

media_info = {git="https://github.com/izderadicka/media_info", optional=true}

[dependencies.simple-file-cache]
#path="../file-cache"
git="https://github.com/izderadicka/simple-file-cache.git"
features=["asynch"]
#version="0.1.3"
optional=true


[features]
default = ["tls", "symlinks", "search-cache"]
tls=["tokio-tls", "native-tls"]
symlinks=["cachedirtree/symlinks"]
search-cache=["cachedirtree"]
transcoding-cache=["simple-file-cache", "bytes"]
libavformat = ["media_info"]

[[bin]]
name = "audioserve"
path = "src/main.rs"